stages:
 - git-update
 - tests

variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "master"
    OCAML: "4_08"
    FRAMA_CI_OPT: "--override frama-clang:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"

#avoid a nix error https://github.com/NixOS/nix/issues/2087
git-update:
  stage: git-update
  script:
   - nix/frama-ci.sh instantiate --eval -A frama-clang.src.outPath
  tags:
   - nix

tests-on-llvm-9:
  stage: tests
  script:
   - nix/frama-ci.sh build -A frama-clang.tests
  tags:
   - nix

tests-on-llvm-10:
  stage: tests
  script:
   - nix/frama-ci.sh build -A frama-clang.on-llvm10.tests
  tags:
   - nix
