stages:
 - git-update
 - tests

variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "master"
    OCAML: "4_08"
    FRAMA_CI_OPT: "--override frama-clang:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"

#avoid a nix error https://github.com/NixOS/nix/issues/2087
git-update:
  stage: git-update
  script:
   - nix/frama-ci.sh instantiate --eval -A frama-clang.src.outPath
  tags:
   - nix

Tests:
  stage: tests
  script:
   - nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/0c0fe6d85b92c4e992e314bd6f9943413af9a309.tar.gz -p nix --run "nix/frama-ci.sh build -A frama-clang.tests"
  tags:
   - nix
