##########################################################################
#                                                                        #
#  This file is part of Frama-Clang                                      #
#                                                                        #
#  Copyright (C) 2012-2020                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file LICENSE).                      #
#                                                                        #
##########################################################################

ENABLE_FRAMA_CLANG=yes
CAMLP5O=camlp5o
CXX=g++
CLANG_CXXFLAGS=-I/usr/lib/llvm-11/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC
CLANG_CFLAGS=-I/usr/lib/llvm-11/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC
CLANG_INCDIR=/usr/lib/llvm-11/include
CLANG_LINKFLAGS=-L/usr/lib/llvm-11/lib 
CLANG_SYSLIBS=
CLANG_BIN_DIR=/usr/lib/llvm-11/bin
LLVM_LIBS=-lLLVM-11
LLVM_VERSION=11.1.0
DEFAULT_FC_C_HEADERS=${prefix}/share/frama-c/libc
DEFAULT_FC_CXX_HEADERS=${prefix}/share/libc++
RUN_TESTS=yes
